# Dependencies
kramdown:
  input: GFM
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Robotics: Science and Systems"
tagline:          'A Robotics Conference'
description:      'July 12-16 2017. Cambridge, USA.'
url:              
baseurl:          /website-hyde
include:          ['_pages']

author:
  name:           'Siddhartha Srinivasa'
  url:            www.cs.cmu.edu/~siddh

gems:             [jekyll-paginate]
paginate:         5
paginate_path:    "blog/page:num"

# Custom vars
version:          2.1.0

github:
  repo:           

collections:
    aommittees:
        output: true
        permalink: /committees/:path/
    attending:
        output: true
        permalink: /attending/:path/
    program:
        output: true
        permalink: /program/:path/
    information:
        output: true
        permalink: /information/:path/
