# Dependencies
kramdown:
  input: GFM
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Robotics: Science and Systems"
tagline:          'A Robotics Conference'
description:      'June 26-30 2018. Pittsburgh, USA.'
url:
baseurl:
include:          ['_pages']
exclude:          ['README.md', 'LICENSE.md', 'Gemfile', 'Gemfile.lock', '.travis.yml', 'vendor', 'GRTAGS', 'GPATH', 'GTAGS', 'deploy.sh']

author:
  name:           'Wennie Tabib'
  url:            www.wtabib.com

gems:             [jekyll-paginate]
paginate:         5
paginate_path:    "blog/page:num"

# Custom vars
version:          2.1.0

github:
  repo:

collections:
    committees:
        output: true
        permalink: /committees/:path/
    attending:
        output: true
        permalink: /attending/:path/
    program:
        output: true
        permalink: /program/:path/
    information:
        output: true
        permalink: /information/:path/

defaults:
  -
    scope:
      path: ""
    values:
      priority: 0
